# Generated by Django 2.2.9 on 2020-03-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_board', '0003_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
