# Generated by Django 2.2.9 on 2020-03-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_type', models.CharField(choices=[('status', 'Status'), ('text', 'Text'), ('rating', 'Rating'), ('date', 'Date'), ('users', 'Users'), ('priority', 'Priority'), ('numbers', 'Numbers'), ('checkbox', 'Checkbox'), ('progress', 'Progress'), ('file', 'File')], max_length=20)),
                ('col_id', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('done', 'Done'), ('in progress', 'In Progress'), ('stuck', 'Stuck')], max_length=20)),
                ('numbers', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True)),
                ('text', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('file', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
