# Generated by Django 2.2.9 on 2020-03-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0003_column_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='priority',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('high', 'High'), ('mid', 'Mid'), ('low', 'Low')], max_length=20),
        ),
    ]
