# Generated by Django 2.2.9 on 2020-03-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0004_column_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='priority',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True),
        ),
    ]
