# Generated by Django 2.2.9 on 2020-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0005_auto_20200302_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='text',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
