# Generated by Django 2.2.9 on 2020-03-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0006_column_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
