# Generated by Django 2.2.9 on 2020-03-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0007_column_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='col_type',
            field=models.CharField(choices=[('status', 'Status'), ('text', 'Text'), ('rating', 'Rating'), ('date', 'Date'), ('users', 'Users'), ('priority', 'Priority'), ('numbers', 'Numbers'), ('checkbox', 'Checkbox'), ('progress', 'Progress'), ('file', 'File')], max_length=20),
        ),
    ]
