# Generated by Django 2.2.9 on 2020-02-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200226_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
